name: Deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'
    paths:
      - 'pkg/deployments/**'

jobs:
  check-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Compile balancer-js
        run: yarn workspace @balancer-labs/balancer-js build
      - name: Check Deployment Artifacts
        run: yarn workspace @balancer-labs/v2-deployments check-artifacts

  check-addresses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Compile balancer-js
        run: yarn workspace @balancer-labs/balancer-js build
      - name: Prepare Config
        run: yarn workspace @balancer-labs/v2-deployments ci:prepare-config
        env:
          MAINNET_RPC_ENDPOINT: ${{ secrets.MAINNET_INFURA_ENDPOINT }}
          POLYGON_RPC_ENDPOINT: ${{ secrets.POLYGON_INFURA_ENDPOINT }}
          ARBITRUM_RPC_ENDPOINT: ${{ secrets.ARBITRUM_INFURA_ENDPOINT }}
          OPTIMISM_RPC_ENDPOINT: ${{ secrets.OPTIMISM_INFURA_ENDPOINT }}
          BINANCE_RPC_ENDPOINT: ${{ secrets.BINANCE_INFURA_ENDPOINT }}
          GNOSIS_RPC_ENDPOINT: ${{ secrets.GNOSIS_INFURA_ENDPOINT }}
          GOERLI_RPC_ENDPOINT: ${{ secrets.GOERLI_INFURA_ENDPOINT }}
      - name: Check Deployment Addresses
        run: yarn workspace @balancer-labs/v2-deployments check-deployments

  check-action-ids:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Compile balancer-js
        run: yarn workspace @balancer-labs/balancer-js build
      - name: Prepare Config
        run: yarn workspace @balancer-labs/v2-deployments ci:prepare-config
        env:
          MAINNET_RPC_ENDPOINT: ${{ secrets.MAINNET_INFURA_ENDPOINT }}
          POLYGON_RPC_ENDPOINT: ${{ secrets.POLYGON_INFURA_ENDPOINT }}
          ARBITRUM_RPC_ENDPOINT: ${{ secrets.ARBITRUM_INFURA_ENDPOINT }}
          OPTIMISM_RPC_ENDPOINT: ${{ secrets.OPTIMISM_INFURA_ENDPOINT }}
          BINANCE_RPC_ENDPOINT: ${{ secrets.BINANCE_INFURA_ENDPOINT }}
          GNOSIS_RPC_ENDPOINT: ${{ secrets.GNOSIS_INFURA_ENDPOINT }}
          GOERLI_RPC_ENDPOINT: ${{ secrets.GOERLI_INFURA_ENDPOINT }}
      - name: Check Action IDs
        run: yarn workspace @balancer-labs/v2-deployments check-action-ids

env:
  CI: true
